[package]
name = "nl-sh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.6.2"
openai-api-rs = "4.0.6"
regex = "1"
